/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "yandex_reviews.index": [],
    "login.show": [],
    "login": [],
    "settings.show": [],
    "settings.update": [],
    "reviews.show": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
